"""
Example demonstrating control-space MPPI implementation.

This script shows how to use the control-space MPPI approach where:
1. Control inputs (accelerations) are sampled
2. Trajectories are generated by forward integration through dynamics
3. Costs are evaluated along the rollouts
4. Optimal controls are computed via information-theoretic weighting

This is the theoretically correct MPPI formulation for control problems.
"""

import numpy as np
import numpy as np
from tamols.tamols_dataclasses import Gait, Terrain, Robot
from tamols import TAMOLS, plot_all_iterations, get_trajectory_function, plot_base
from tamols.helpers import transform_inertia
from tamols.manual_heightmaps import get_flat_heightmap, get_stairs_heightmap
from tamols.map_processing import save_heightmap_to_png
from tamols.mppi_control_space import QuadrupedControlSpaceMPPI, extract_trajectory_from_control_rollout


def run_control_space_mppi_example():
    """Run control-space MPPI example."""
    
    print("=" * 60)
    print("Control-Space MPPI Example for Quadruped Locomotion")
    print("=" * 60)
    print()
    
    # Define gait parameters
    gait = Gait(
        n_steps=3,
        n_phases=2,
        spline_order=5,
        tau_k=np.array([1.0, 1.0]),
        h_des=0.445,
        eps_min=0.1,
        weights=np.array([10.0e4, 0.001, 7.0, 100.0, 3.0, 0.01, 2.0, 0.001]),
        desired_base_velocity=np.array([0.3, 0.0, 0.0]),
        desired_base_angular_velocity=np.array([0.0, 0.0, 0.0]),
        apex_height=0.1,
        contact_schedule=np.array([
            [0, 1, 1, 0],
            [1, 0, 0, 1],
        ]),
        at_des_position=np.array([
            [1, 0, 0, 1],
            [1, 1, 1, 1],
        ])
    )
    
    # Define terrain (flat for simplicity in this demo)
    h = np.array(get_flat_heightmap(a=150, b=150, height=0.0))
    
    terrain = Terrain(
        heightmap=h,
        grid_cell_length=0.04,
        mu=0.6,
        gravity=np.array([0.0, 0.0, -9.81]),
    )
    
    # Define robot parameters
    I_A = np.diag(np.array([0.107027, 0.0980771, 0.0244531]))
    r = np.array([0.021112, 0, -0.005366])
    q = np.array([-0.000543471, 0.713435, -0.00173769, 0.700719])
    mass = 6.921
    
    robot = Robot(
        mass=mass,
        inertia=transform_inertia(I_A, mass, r, q),
        l_min=0.1,
        l_max=0.5,
        r_1=np.array([0.1934, 0.0465+0.0955, 0.0]),
        r_2=np.array([0.1934, -0.0465-0.0955, 0.0]),
        r_3=np.array([-0.1934, 0.0465+0.0955, 0.0]),
        r_4=np.array([-0.1934, -0.0465-0.0955, 0.0]),
        p_1_start=np.array([0.1934, 0.0465+0.0955, 0.0]),
        p_2_start=np.array([0.1934, -0.0465-0.0955, 0.0]),
        p_3_start=np.array([-0.1934, 0.0465+0.0955, 0.0]),
        p_4_start=np.array([-0.1934, -0.0465-0.0955, 0.0]),
        initial_base_pose=np.array([0.0, 0.0, 0.445, 0.0, 0.0, 0.0]),
        initial_base_velocity=np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0]),
    )
    
    print("\n" + "=" * 60)
    print("Approach 1: State-Space MPPI (Original)")
    print("=" * 60)
    print("Samples spline coefficients and foot positions directly")
    print()
    
    # Run state-space MPPI
    problem_state = TAMOLS(
        gait, terrain, robot,
        num_samples=500,
        num_iterations=30,
        use_control_space_mppi=False
    )
    
    print("Running state-space MPPI optimization...")
    sols_state, infos_state = problem_state.run_repeated_optimizations(warm_start=False)
    
    print("\nState-space MPPI results:")
    for i, info in enumerate(infos_state):
        print(f"  Step {i+1}: objective = {info['obj_val']:.6f}, status = {info['status']}")
    
    print("\n" + "=" * 60)
    print("Approach 2: Control-Space MPPI (New)")
    print("=" * 60)
    print("Samples control inputs and propagates through dynamics")
    print()
    
    # Run control-space MPPI
    problem_control = TAMOLS(
        gait, terrain, robot,
        num_samples=500,
        num_iterations=30,
        use_control_space_mppi=True,
        control_horizon=20
    )
    
    print("Running control-space MPPI optimization...")
    sols_control, infos_control = problem_control.run_repeated_optimizations(warm_start=False)
    
    print("\nControl-space MPPI results:")
    for i, info in enumerate(infos_control):
        print(f"  Step {i+1}: objective = {info['obj_val']:.6f}, status = {info['status']}")
    
    print("\n" + "=" * 60)
    print("Comparison")
    print("=" * 60)
    
    avg_obj_state = np.mean([info['obj_val'] for info in infos_state])
    avg_obj_control = np.mean([info['obj_val'] for info in infos_control])
    
    print(f"State-space MPPI average objective: {avg_obj_state:.6f}")
    print(f"Control-space MPPI average objective: {avg_obj_control:.6f}")
    
    # Generate and save visualizations
    print("\nGenerating visualizations...")
    
    # Save heightmap
    save_heightmap_to_png(terrain.heightmap, "outputs/heightmap_control_space.png")
    
    # Plot trajectories
    plot_base(sols_control, problem_control, dt=0.02)
    plot_all_iterations(sols_control, problem_control, dt=0.02)
    
    # Extract trajectory data
    trajectory_fn = get_trajectory_function(sols_control, problem_control)
    time, feet_positions, base_positions, base_rotations = trajectory_fn(0.02)
    
    print(f"\nTrajectory generated:")
    print(f"  Duration: {time[-1]:.2f} seconds")
    print(f"  Timesteps: {len(time)}")
    print(f"  Base position range: [{base_positions[:, 0].min():.2f}, {base_positions[:, 0].max():.2f}] m")
    
    print("\n" + "=" * 60)
    print("Direct Control-Space MPPI Usage")
    print("=" * 60)
    print("Using QuadrupedControlSpaceMPPI directly (without TAMOLS wrapper)")
    print()
    
    # Demonstrate direct usage of control-space MPPI
    control_mppi = QuadrupedControlSpaceMPPI(
        gait=gait,
        terrain=terrain,
        robot=robot,
        horizon=20,
        num_samples=500,
        num_iterations=30,
    )
    
    # Prepare initial state
    initial_state = np.concatenate([
        np.asarray(robot.initial_base_pose),
        np.asarray(robot.initial_base_velocity),
        np.asarray(robot.p_1_start),
        np.asarray(robot.p_2_start),
        np.asarray(robot.p_3_start),
        np.asarray(robot.p_4_start),
    ])
    
    target_velocity = np.concatenate([
        np.asarray(gait.desired_base_velocity),
        np.asarray(gait.desired_base_angular_velocity),
    ])
    
    print("Optimizing control sequence...")
    controls, info = control_mppi.optimize_trajectory(initial_state, target_velocity)
    
    print(f"Optimization completed: {info['message']}")
    print(f"Final cost: {info['final_cost']:.6f}")
    print(f"Iterations: {info['iterations']}")
    
    # Integrate to get full trajectory
    states, _ = control_mppi.integrate_controls_to_trajectory(initial_state, controls)
    
    # Extract trajectory components
    traj_dict = extract_trajectory_from_control_rollout(states, gait, robot)
    
    print(f"\nGenerated trajectory:")
    print(f"  Steps: {states.shape[0]}")
    print(f"  Base position: {traj_dict['base_positions'][0]} -> {traj_dict['base_positions'][-1]}")
    print(f"  Base velocity: {traj_dict['base_velocities'][0][:3]} -> {traj_dict['base_velocities'][-1][:3]}")
    
    print("\n" + "=" * 60)
    print("Example complete!")
    print("=" * 60)
    print("\nKey differences:")
    print("  1. State-space: Samples spline coefficients directly")
    print("  2. Control-space: Samples accelerations and integrates dynamics")
    print("  3. Control-space is theoretically correct MPPI formulation")
    print("  4. Both approaches can leverage GPU acceleration")
    print()


if __name__ == "__main__":
    run_control_space_mppi_example()
